local function reset()
  package.loaded["jam.output"] = nil
end

describe("T-34 | ANSI escape code stripping", function()
  before_each(reset)

  it("strips a basic SGR escape sequence", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-basic]")
    out.clear(buf)
    out.append(buf, { "\27[1;34mINFO\27[m" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("INFO")
  end)

  it("strips bold/reset sequences", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-bold]")
    out.clear(buf)
    out.append(buf, { "\27[1mBUILD SUCCESS\27[0m" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("BUILD SUCCESS")
  end)

  it("strips carriage returns", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-cr]")
    out.clear(buf)
    out.append(buf, { "line one\r" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("line one")
  end)

  it("strips ANSI and carriage returns together", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-combined]")
    out.clear(buf)
    out.append(buf, { "\27[1;34mINFO\27[m loading\r" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("INFO loading")
  end)

  it("leaves plain text unchanged", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-plain]")
    out.clear(buf)
    out.append(buf, { "no escapes here" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("no escapes here")
  end)

  it("handles multiple lines in one append call", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-multi]")
    out.clear(buf)
    out.append(buf, { "\27[32mline A\27[0m", "\27[31mline B\27[0m" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("line A")
    expect(lines[2]).to_be("line B")
  end)

  it("strips the standard Maven color INFO prefix", function()
    local out = require("jam.output")
    local buf = out.get_or_create("[jam:ansi-maven]")
    out.clear(buf)
    out.append(buf, { "\27[1;34m[INFO]\27[m Building myapp" })
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    expect(lines[1]).to_be("[INFO] Building myapp")
    expect(lines[1]:find("\27")).to_be_nil()
  end)
end)
